# Generated by Django 3.2.3 on 2021-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=1000)),
            ],
        ),
    ]
